### ISSUE TITLE
掘金的貌似新版不在显示目录了~

### ISSUE THREAD

**Issue by FrizzleFur** [zhilidali/TreeBar#3]
非常感谢作者，简书的正常，但是新版的掘金上了沸点后，貌似不显示目录了，希望有空看到回复下，谢谢！

**Comment by zhilidali** [comment]
TreeBar 版本号是多少？方便的话可以提供一个要显示目录的掘金url

**Comment by FrizzleFur** [comment]
刚看到，版本是V0.1.6,应该是最新的。

问题是：
1. 比如这篇有掘金自带的目录[没朋友(mpvue)，点个外卖，一个人也要好好吃饭](https://juejin.im/post/5b3027cce51d4558c65216a9#heading-4)是可以显示目录的。

2. 但是这篇没有目录[HTML5.2新标签 —— dialog - 前端 - 掘金](https://juejin.im/entry/5b34a26e51882574dd4ae3b1) 就无法获取目录了。

是不是依赖掘金的目录呢?

**Comment by zhilidali** [comment]
谢谢反馈，已修复，请更新到 0.1.7 版本

**Comment by FrizzleFur** [comment]
非常棒👍，已经可以了，谢谢作者大大。
