### ISSUE TITLE
少数派网站貌似已经失效

### ISSUE THREAD

**Issue by hqz0502** [zhilidali/TreeBar#7]
在少数派的网站上阅读文章时，不再显示目录树导航了，已经有一段时间了，不知是何原因。
另外，能不能支持对 Notion 分享页面的目录获取？
感谢！

**Comment by jssyxzy** [comment]
同

**Comment by YangJunWeifromchina** [comment]
可以适配CSDN吗 期待

**Comment by zhilidali** [comment]
少数派 已 fixed，请更新至 0.1.10
