### ISSUE TITLE
简书页面不成功

### ISSUE THREAD

**Issue by liujiakuo** [zhilidali/TreeBar#8]
你好.那个目录树项目,在件数中报错如下

index.html:167 Uncaught TypeError: Cannot read property 'querySelectorAll' of null
    at Object.init (index.html:167)
    at HTMLDocument.document.onreadystatechange (index.html:186)

**Comment by zhilidali** [comment]
可以帮忙提供下 所用的浏览器版本、访问页面 等环境吗？

**Comment by listenkeep** [comment]
同样的问题，我看了一下，主要是简书css样式修改了

问题发生点：
init: function() {
	console.time('TreeBar');
	// 1. 获取DOM
	var hList = document.querySelector(treeBar.site.tagName)
					.querySelectorAll('h1, h2, h3, h4, h5, h6');

简书页面的tagName和当前简书页面不匹配
然而，现在简书的css样式改为如:'_21bLU4 _3kbg6I'/'_3VRLsv'
按当前的获取元素策略，恐怕很难受，我也没啥好想法尽量少改动

**Comment by zhilidali** [comment]
已临时更改了简书的 tagName，请更新到 0.1.11 版本重试。

鉴于越来越多的用户使用了此脚本，我有了重写此脚本的动力，如果你们有什么建议的话，欢迎指出不足，以及一起贡献此仓库
